experiment: "smalltest_dataset"

# data_dir: "foo/train_sm"
# data_frames: "foo/train_sm.xlsx"
# validator_data_dir: "foo/val"
# validator_data_frames: "foo/val.xlsx"

# forward slashes, even on Windows!
data_dir: "C:/Lonce/deleteme/smset/smset/train_sm"
data_frames: "C:/Lonce/deleteme/smset/smset/train_sm.xlsx"
validator_data_dir: "C:/Lonce/deleteme/smset/smset/val"
validator_data_frames: "C:/Lonce/deleteme/smset/smset/val.xlsx"


TransformerClass: "RopeCondDACTransformer" 

ftype: 'dac' # dac or mel
vocab_size: 1024
input_type: "int" # int (for tokens), or "float" (for decoded tokens or mel spectrograms, etc)
num_tokens: 4

cond_params: 1 #1 (not counting the classes)
model_size: 256 # must be divisible by num_heads

Ti: 86 # 172 #86
Tt: 430 # must match the length of the sequences in the batch
batch_size: 4  #**

num_layers: 2 #**
num_heads: 8 #8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 4 #4 #4
dropout_rate: 0.2
learning_rate: 0.0005
use_adaLN: True #else FiLM

num_epochs: 30 ### 800 

ErrorLogRate: 1 ### 10
checkpoint_interval: 5 ###50 # 25

