experiment: "syntex_sm_mel_smoothing"
#testsnd: Chirp DSApp DSBug DSPee DSPis DSWin TokWo

data_dir: "/home/lonce/scratchdata/syntexnew/data7mel/train_sm"
data_frames: "/home/lonce/scratchdata/syntexnew/data7mel/train_sm.xlsx"
validator_data_dir: "/home/lonce/scratchdata/syntexnew/data7mel/val"
validator_data_frames: "/home/lonce/scratchdata/syntexnew/data7mel/val.xlsx"

TransformerClass: "RopeCondDACTransformer" 

# ftype: 'dac' # dac or mel
# vocab_size: 1024
# input_type: "int"
# num_tokens: 4

ftype: 'mel' # dac or mel
vocab_size: 128
input_type: "float"
num_tokens: 1

model_size: 256 # must be divisible by num_heads

Ti: 86 # 172 #86
Tt: 429 # must match the length of the sequences in the batch
batch_size: 24  #**


num_layers: 3 #**
num_heads: 8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 4 # 4 #4
dropout_rate: 0.2
learning_rate: 0.0005
use_adaLN: False #else FiLM

num_epochs: 2000 ### 800 

ErrorLogRate: 20 ### 10
checkpoint_interval: 200 ###50 # 25

