experiment: "mini_test_2"

data_dir: "/home/lonce/scratchdata/Lala_data/lala_mel"
data_frames: "/home/lonce/scratchdata/Lala_data/lala_class_train_mel.xlsx"
validator_data_dir: null
validator_data_frames: null

TransformerClass: "RopeCondDACTransformer" 

ftype: 'mel' # dac or mel
vocab_size: 128
input_type: "float"
num_tokens: 1

#cond_params: 1 #1 (not counting the classes)
model_size: 64 # must be divisible by num_heads

Ti: 43 # 172 #86 mask size for training and training, mask and windowsize for inference 
Tt: 429 # must match the length of the sequences in the batch
batch_size: 4  #**


num_layers: 2 #**
num_heads: 4 #8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 2 #4 #4
dropout_rate: 0.2
learning_rate: 0.0005
use_adaLN: False #else FiLM

num_epochs: 20 ### 800 

ErrorLogRate: 1 #2 ### 10
checkpoint_interval: 20 ###50 # 25

